export const Color = {
    bgColor: "#f0f6fb",
    softSecBgPrimary: "#bcd3e6",
    softGreyBgPrimary: "#cbcdd1",
    primaryColor: "#216dab",
    softPrimaryColor: "#6499c4",
    secColor: "#9cd2ff",
    softSecColor: "#d7edff",
    darkTextColor: "#4d5963",
    lightTextColor: "#f0f6fb",
    bgSuccessColor: "#e9faec",
    boldSuccessColor: "#1fcc44",
    successColor: "#4cd669",
    bgErrorColor: "#fae9e7",
    boldErrorColor: "#cc1f12",
    errorColor: "#d64c41",
    bgInfoColor: "#d0dbf5",
    boldInfoColor: "#124ccc",
    infoColor: "#5982db",
    bgWarningColor: "#fbf6e8",
    boldWarningColor: "#d9a318",
    warningColor: "#e1b546",
    bgNeutralColor: "#dbdee0",
    neutralColor: "#828b92",
    primaryDisableColor: "#6499c4"
}