export const shipLocationSeed = [
    { value: 'Ambon - Maluku' },
    { value: 'Balikpapan - Kalimantan Timur' },
    { value: 'Banda Aceh - Aceh' },
    { value: 'Bandar Lampung - Lampung' },
    { value: 'Bandung - Jawa Barat' },
    { value: 'Banjar - Jawa Barat' },
    { value: 'Banjarbaru - Kalimantan Selatan' },
    { value: 'Banjarmasin - Kalimantan Selatan' },
    { value: 'Batam - Kepulauan Riau' },
    { value: 'Batu - Jawa Timur' },
    { value: 'Bau-Bau - Sulawesi Tenggara' },
    { value: 'Bekasi - Jawa Barat' },
    { value: 'Bengkulu - Bengkulu' },
    { value: 'Bima - Nusa Tenggara Barat' },
    { value: 'Binjai - Sumatera Utara' },
    { value: 'Bitung - Sulawesi Utara' },
    { value: 'Blitar - Jawa Timur' },
    { value: 'Bogor - Jawa Barat' },
    { value: 'Bontang - Kalimantan Timur' },
    { value: 'Bukittinggi - Sumatera Barat' },
    { value: 'Cilegon - Banten' },
    { value: 'Cimahi - Jawa Barat' },
    { value: 'Cirebon - Jawa Barat' },
    { value: 'Denpasar - Bali' },
    { value: 'Depok - Jawa Barat' },
    { value: 'Dumai - Riau' },
    { value: 'Gorontalo - Gorontalo' },
    { value: 'Gunungsitoli - Sumatera Utara' },
    { value: 'Jakarta - Jakarta' },
    { value: 'Jambi - Jambi' },
    { value: 'Jayapura - Papua' },
    { value: 'Kediri - Jawa Timur' },
    { value: 'Kendari - Sulawesi Tenggara' },
    { value: 'Kotamobagu - Sulawesi Utara' },
    { value: 'Kupang - Nusa Tenggara Timur' },
    { value: 'Langsa - Aceh' },
    { value: 'Lhokseumawe - Aceh' },
    { value: 'Lubuklinggau - Sumatera Selatan' },
    { value: 'Madiun - Jawa Timur' },
    { value: 'Magelang - Jawa Tengah' },
    { value: 'Makassar - Sulawesi Selatan' },
    { value: 'Malang - Jawa Timur' },
    { value: 'Manado - Sulawesi Utara' },
    { value: 'Mataram - Nusa Tenggara Barat' },
    { value: 'Medan - Sumatera Utara' },
    { value: 'Metro - Lampung' },
    { value: 'Mojokerto - Jawa Timur' },
    { value: 'Padang - Sumatera Barat' },
    { value: 'Padang Panjang - Sumatera Barat' },
    { value: 'Padang Sidempuan - Sumatera Utara' },
    { value: 'Pagar Alam - Sumatera Selatan' },
    { value: 'Palangkaraya - Kalimantan Tengah' },
    { value: 'Palembang - Sumatera Selatan' },
    { value: 'Palopo - Sulawesi Selatan' },
    { value: 'Palu - Sulawesi Tengah' },
    { value: 'Pangkal Pinang - Kepulauan Bangka Belitung' },
    { value: 'Parepare - Sulawesi Selatan' },
    { value: 'Pariaman - Sumatera Barat' },
    { value: 'Pasuruan - Jawa Timur' },
    { value: 'Payakumbuh - Sumatera Barat' },
    { value: 'Pekalongan - Jawa Tengah' },
    { value: 'Pekanbaru - Riau' },
    { value: 'Pematangsiantar - Sumatera Utara' },
    { value: 'Pontianak - Kalimantan Barat' },
    { value: 'Prabumulih - Sumatera Selatan' },
    { value: 'Probolinggo - Jawa Timur' },
    { value: 'Sabang - Aceh' },
    { value: 'Salatiga - Jawa Tengah' },
    { value: 'Samarinda - Kalimantan Timur' },
    { value: 'Sawahlunto - Sumatera Barat' },
    { value: 'Serang - Banten' },
    { value: 'Sibolga - Sumatera Utara' },
    { value: 'Singkawang - Kalimantan Barat' },
    { value: 'Solok - Sumatera Barat' },
    { value: 'Sorong - Papua Barat' },
    { value: 'Subulussalam - Aceh' },
    { value: 'Sukabumi - Jawa Barat' },
    { value: 'Sungaipenuh - Jambi' },
    { value: 'Surabaya - Jawa Timur' },
    { value: 'Surakarta - Jawa Tengah' },
    { value: 'Tangerang - Banten' },
    { value: 'Tangerang Selatan - Banten' },
    { value: 'Tanjungbalai - Sumatera Utara' },
    { value: 'Tanjungpinang - Kepulauan Riau' },
    { value: 'Tarakan - Kalimantan Utara' },
    { value: 'Tasikmalaya - Jawa Barat' },
    { value: 'Tebingtinggi - Sumatera Utara' },
    { value: 'Tegal - Jawa Tengah' },
    { value: 'Ternate - Maluku Utara' },
    { value: 'Tidore Kepulauan - Maluku Utara' },
    { value: 'Tomohon - Sulawesi Utara' },
    { value: 'Tual - Maluku' },
    { value: 'Yogyakarta - Yogyakarta' },
];
